[connections.mysql]
dialect = "mysql"
host = "mysql-104f94f-mamaa-05.h.aivencloud.com"
port = 17567
database = "mamaa"
username = "avnadmin"
password = "AVNS_eTYy8GEwyO7dZHa-CFs"
query = { charset = "utf8mb4" }